### ISSUE TITLE
Importing chart.js

### ISSUE THREAD

**Issue by dwood7399** [plondon/BlackMirror#3]
Thanks for sharing this! I've been adapting it a bit and have been struggling to get chart.js added. I want to use it to show a graph of the forecast with hourly forecast.io data.

If you have a minute would you mind letting me know if I'm on the right track? I installed with npm and mimicked the Backbone and undersccore imports in main.js. I really appreciate it.

`````` require.config({
    baseUrl: "/js/app",
    paths: {
        "jquery": "../lib/jquery.min",
        "underscore": "../lib/underscore",
        "backbone": "../lib/backbone",
        "chartjs":"../../node_modules/chart.js/src/chart"
    },
    shim: {
        jquery: {
          exports: "$"
        },
        underscore: {
          deps: ["jquery"],
          exports: "_"
        },
        backbone: {
          deps: ["jquery", "underscore"],
          exports: "Backbone"
        },
        chartjs: {
          deps: ["jquery","underscore", "backbone"],
          exports: "Chart"
        }
    },
    urlArgs: "bust=" + (new Date()).getTime(),
    waitSeconds: 0
});

require([
    "jquery",
    "underscore",
    "backbone",
    "chartjs"
], function($, _, Backbone, Chart) {
    require(['app'], function() {});

}); ```
``````

**Comment by plondon** [comment]
Hey @dwood7399 thanks for checking out the project and cool idea.

I'm not sure why require won't work, but you don't have to use it to include Chart.js. You can also drop `<script src="node_modules/chart.js/dist/Chart.js"></script>` in the head tag in index.html and then use `new Chart({})` anywhere in weather.js.

Hope that helps!

**Comment by dwood7399** [comment]
Thanks @plondon! 

I got require to work, turns out I was just referencing `node_modules/chart.js/src/chart.js` instead of `node_modules/chart.js/dist/Chart.js` ...😒  

I'll add to github when I'm finished.
